### ISSUE TITLE
Incorrect Twiss computation for periodic lattice

### ISSUE THREAD

**Issue by chernals** [ULB-Metronu/zgoubidoo#13]
Apparently, the issue only appears for periodic lattices.

- [ ] weird phase jump
- [ ] negative beta

**Comment by rtesse** [comment]
@marionvanwelde Could you comment on this ?

**Comment by chernals** [comment]
Multiple fixes in the Twiss module have been added.

Re create a new issue if it re appears. Also will be fixed by Marion's code for the coupling ?
